name: build_and_publish_docker_image

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: hub.docker.com
  DOCKER_IMAGE: liamnou/hemnet_parser_bot_armv7
  DOCKER_TARGET_PLATFORM: linux/arm/v7

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Prepare
      if: success()
      id: prepare
      run: |
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}

    - name: Login to DockerHub
      if: success()
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run Buildx (build & push)
      if: success()
      run: |
        docker buildx build \
        --platform ${{ steps.prepare.outputs.docker_platform }} \
        --tag ${DOCKER_IMAGE}:${{ steps.prepare.outputs.version }} \
        --file ./Dockerfile.arm \
        --output type=image,push=true .
